### ISSUE TITLE
Umbrella Features ☂️

### ISSUE THREAD

**Issue by lukebrandonfarrell** [Fitpassu/react-native-stripe-payments#2]
## Details

Opening this issue so we can coordinate development in this library in order to build all the missing features for full SCA using Stripe. The goal is to add all the missing pieces to the library for the 1st of September.

@viktorasl let me know what you think of the following API:

```
// Setup Intent
setupPayment(clientSecret, cardDetails)
// Using card details on the fly
confirmPaymentWithCard(clientSecret, cardDetails)
// Using existing card
confirmPaymentWithId(clientSecret, paymentMethodId)
```

## Tasks

- [x] Setup Intents on iOS 
Setup intents is almost the same setup on iOS as the payment intents, we need to pass card details through to the native side, support billing details, and return a card object on successful creation.
- [x] Payment Intents Support ID on iOS
Currently the payment intents only supports taking an object of card details. We can modify [this function](https://github.com/Fitpassu/react-native-stripe-payments/blob/master/ios/StripePayments.m#L25) to make `cardParams` optional and add a parameter called paymentMethodId, depending on which parameter is present, we can create the `STPPaymentIntentParams`. This will allow us to `confirmPayment` with card details or an existing card.

The same above is true for Android:

- [x] Setup Intents on Android 
- [x] Payment Intents Support ID on Android
Change [this function here](https://github.com/Fitpassu/react-native-stripe-payments/blob/master/android/src/main/java/com/fitpassu/stripepayments/StripePaymentsModule.java#L81) to support optionally either `cardParams` or `paymentMethodId`. 

- [x] [TypeScript API](https://github.com/Fitpassu/react-native-stripe-payments/blob/master/lib/index.tsx)

If I have missed any important features, please let me know in the comments.

**Comment by 0xamogh** [comment]
Hey guys, Amogh here. Worked with @lukebrandonfarrell on the native Android aspect of our version of this library, would be cool if we could continue developing it and be able to launch it as a production-level alternative to tipsi-stripe 😄

**Comment by viktorasl** [comment]
Looks great! Generally I'm iOS developer so if you have less resources regarding iOS development I can help.

As production ready as tipsi is will be hard to implement as there are quite a lot of edge cases and extra functionalities build around Stripe (i.e fraudulent activity middleware) 😄 

But I believe this library can find it's niche in the market 👍

**Comment by lukebrandonfarrell** [comment]
@viktorasl Sounds good. We have the iOS implementation already done in Swift, so just need to make the conversion. I'll attach you in to review the PR for iOS side.

As for a note to myself, we need to support Diners Club cards which our native implementation has trouble with at the moment.

**Comment by lukebrandonfarrell** [comment]
Finished the implementation over at: https://github.com/aspect-apps/react-native-stripe-payments (@viktorasl) will make a PR in next week.
